version: "3.8"

services:
    app:
        build: .
        container_name: laravel-app
        ports:
            - "8000:8000" # maps container port 8000 to host
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel_db
            DB_USERNAME: root
            DB_PASSWORD: secret
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
