version: "3.8"

services:
    app:
        build: .
        container_name: laravel-app
        ports:
            - "8000:8000" # maps container port 8000 to host
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: reward_management
            DB_USERNAME: root
            DB_PASSWORD:
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network
mysql:
    image: mysql:8
    restart: always
    environment:
        MYSQL_DATABASE: reward_management
        MYSQL_ROOT_PASSWORD: 
    ports:
        - "3306:3306"
networks:
    laravel-network:
        driver: bridge
